# Default values for nginx.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
replicaCount: 1
restartPolicy: Never

index: >-
  <h1>Hello</h1>
  <p>This is a test</p>

image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8888
  nodePort: ""
