apiVersion: v1
kind: Pod
metadata:
  name: nginx-mc
  labels:
    env: demo
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - name: http
      containerPort: 80
    volumeMounts:
    - name: content
      mountPath: /usr/share/nginx/html
  - name: content-writer
    image: debian
    volumeMounts:
    - name: content
      mountPath: /html
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
            echo "<h1>Current time:$(date +%T)</h1>" > /html/index.html;
          sleep 1;
        done
  volumes:
  - name: content
    emptyDir: {}